# Generated by Django 4.0.6 on 2022-08-10 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImovelTbl',
            fields=[
                ('idt_imovel', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc_endereco', models.CharField(max_length=400)),
                ('desc_status', models.CharField(max_length=20)),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Imóveis',
                'db_table': 'imovel_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InquilinoTbl',
            fields=[
                ('idt_inquilino', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc_nome', models.CharField(max_length=50)),
                ('desc_tipo', models.CharField(max_length=4)),
                ('desc_status', models.CharField(max_length=20)),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('dt_vencimento', models.DateField()),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Inquilino',
                'db_table': 'inquilino_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReformaTbl',
            fields=[
                ('idt_reforma', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_reforma', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('desc_reforma', models.CharField(max_length=1000)),
                ('dt_reforma', models.DateField()),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('idt_imovel', models.ForeignKey(blank=True, db_column='idt_imovel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='innapp.imoveltbl')),
            ],
            options={
                'verbose_name': 'Reforma',
                'db_table': 'reforma_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AluguelTbl',
            fields=[
                ('idt_aluguel', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_aluguel', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('num_administracao', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('num_acordo', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('dt_recebimento', models.DateField()),
                ('dt_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('idt_imovel', models.ForeignKey(blank=True, db_column='idt_imovel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='innapp.imoveltbl')),
                ('idt_inquilino', models.ForeignKey(blank=True, db_column='idt_inquilino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='innapp.inquilinotbl')),
            ],
            options={
                'verbose_name': 'Aluguel',
                'db_table': 'aluguel_tbl',
                'managed': True,
            },
        ),
    ]
