# Generated by Django 4.0.6 on 2022-09-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innapp', '0002_remove_inquilinotbl_dt_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alugueltbl',
            name='mes_referencia',
            field=models.IntegerField(default=1),
        ),
    ]
